### ISSUE TITLE
Unicode Characters and Text Alignment

### ISSUE THREAD

**Issue by Mochnant** [doakey3/DashTable#10]
Not sure if it is something I am doing wrong, but I've noticed that accented characters seem to throw off the spacing.

```
+-----+------------------------+-------+
| ID  | Name                   | Email |
+=====+========================+=======+
| x6  | Hervé de Miremont     |       |
+-----+------------------------+-------+
| x9  | Gilles Sansac          |       |
+-----+------------------------+-------+
| x1  | André Monluc          |       |
+-----+------------------------+-------+
| x8  | Claude Ambleville      |       |
+-----+------------------------+-------+
| x2  | Jean de Sisieulx       |       |
+-----+------------------------+-------+
| x10 | André de Boutteville  |       |
+-----+------------------------+-------+
| x3  | Antonie de Veniers     |       |
+-----+------------------------+-------+
| x4  | Jean-Louis de Clermont |       |
+-----+------------------------+-------+
| x5  | André de Bouillon     |       |
+-----+------------------------+-------+
| x7  | Jacques de Sarzay      |       |
+-----+------------------------+-------+
```

The names are stored in a json file and loaded json.load().

```
        "id": "x10",
        "name": "Andr\u00c3\u00a9 de Boutteville",
```

Thank you.

**Comment by Mochnant** [comment]
I also tried storing the json differently, with no luck:

```
+------+----------------------+
| ID   | Name                 |
+======+======================+
| x3   | Gilles de la Chambre |
+------+----------------------+
| x2   | Jean d'Auriac        |
+------+----------------------+
| x1   | Pierre d'Antin       |
+------+----------------------+
| x4   | Guy Brantôme        |
+------+----------------------+
```

```
        "id": "x4",
        "name": "Guy Brantôme",
```

**Comment by Mochnant** [comment]
I was able to make this work by adding explicit encoding to the loading of the json and saving of the text table.

I'll leave this open for the moment in case there is anything to do on the code side.

**Comment by doakey3** [comment]
I had written a line of code that limited characters to ascii. I can't remember why... I have removed that line. Let me know if it solves the issue.

**Comment by Mochnant** [comment]
Thank you!

Apologies, though, I should have specified I was using data3rst().  It looks like commit ca846ad60295c0e2b7c39771b7ec58528bb35248 is focused on the html2 functions.  I have not used them, so it may be that there was a similar issue there that you've fixed.

That said, with the data2*() functions, the explicit encoding on open() seems to have corrected it on my end.

**Comment by doakey3** [comment]
Very good. I will close this issue then.

**Comment by Mochnant** [comment]
Thank you for your help, @doakey3!
