### ISSUE TITLE
[Feature Request]  Center String in Cell in data2rst()

### ISSUE THREAD

**Issue by Mochnant** [doakey3/DashTable#11]
It would be useful if there was an option to center strings when using data2rst().  Due to the variable width, it would be difficult to do this outside of dashtable.

Thank you for considering.

**Comment by doakey3** [comment]
Should there be a global option for centering all cells, or do you think there should be a way to do it on a per-column basis?

**Comment by Mochnant** [comment]
For my usage, a parameter to data2rst() (aka the global option) would be sufficient.  If you were looking to make it more widely useful, you could add a column, row and/or individual cells (like spans are done).  I could see a use for all of them.

That said, the global option seems simplest, so it may depend on how much development time is available.

Thanks!

**Comment by doakey3** [comment]
I've updated the code. Please check it out and see if it behaves like you'd want it to.

**Comment by Mochnant** [comment]
I'll have to test this manually later, but looking at code changes in 737c37a417c706df63ded8c36802e884f81bc7af it looks perfect.

Thank you so much for the quick enhancement!

**Comment by Mochnant** [comment]
I can confirm this works as expected and meets my needs.

Thank you!

**Comment by Mochnant** [comment]
Any idea when it will make it to pypi?

**Comment by doakey3** [comment]
I just uploaded it now. Thanks for the input.
