### ISSUE TITLE
Cast Numbers to Strings

### ISSUE THREAD

**Issue by Mochnant** [doakey3/DashTable#12]
```dashtable.data2rst.TableContentError: Table must be a list of lists of strings```

There may be a technical reason why, but it seems like forcing the input to be strings only could be avoided if numbers were cast using str().

That is what I do in my code to "fix" this error.

Thanks for considering the improvement!

**Comment by doakey3** [comment]
Ok, I made it so that data is converted to strings automatically. I can't see a good reason to keep throwing an error. Edit: I closed this a bit too quick. I should check with you first to see if it's ok...

**Comment by Mochnant** [comment]
Much appreciated, @doakey3!
