### ISSUE TITLE
Python 2 compatibility

### ISSUE THREAD

**Issue by meyermj** [doakey3/DashTable#13]
Nice module! I think this is very nearly compatible with python 2. It would just take adding

`from __future__ import print_function, division`

as the first import in the appropriate places. I had an error crop up when running in python 2 where a float was returned where an int was required (in dashutils/center_line.py). Works great in python 3, but would be a nice feature to make it backward compatible.

**Comment by doakey3** [comment]
I just made some edits. Try upgrading to the most recent version and let me know if you still have problems.
