### ISSUE TITLE
spans is required for data2rst

### ISSUE THREAD

**Issue by Mochnant** [doakey3/DashTable#14]
I upgraded from 1.3.4 to 1.4.4 and I noticed all calls to data2rst() were now causing errors.

```ERROR: Spans must be a [Row, Column] pair of integers```

Doing a little research, it appears that the 'spans' parameter is now required, though it seems to have a default internally.  Adding spans=[] fixes the issue and allows the table to render.

Sample code using Python 3.6.5 and dashtable 1.4.4:

```
import dashtable

table = [["H1", "H2", "H3", "H4", "H5"]]

table.append(["1", "2", "3", "4", "5"])
table.append(["1", "2", "3", "4", "5"])

print(dashtable.data2rst(table))
print(dashtable.data2rst(table, spans=[]))
```

Output:
```
ERROR: Spans must be a [Row, Column] pair of integers
+----+----+----+----+----+
| H1 | H2 | H3 | H4 | H5 |
+====+====+====+====+====+
| 1  | 2  | 3  | 4  | 5  |
+----+----+----+----+----+
| 1  | 2  | 3  | 4  | 5  |
+----+----+----+----+----+
```

I didn't see any sign this was intentional, and the docs still indicate it is optional.

```
table (list of lists of str) –
spans (list of lists of lists of int, optional) –
```

http://dashtable.readthedocs.io/en/latest/Code.html#dashtable.data2rst

**Comment by doakey3** [comment]
Spans should be an optional parameter. I have made an update. Try it and let me know if you have any trouble.

**Comment by Mochnant** [comment]
Thank you for the quick fix!  I can confirm this is working as expected in v1.4.5 (744cfb6a717fa75a8092c83ebcd49b2668023681).
