### ISSUE TITLE
[Feature] span more than consecutive cells

### ISSUE THREAD

**Issue by arielzn** [doakey3/DashTable#15]
Thanks for this great library, is the only one I found to print tables allowing spans, a great addon for complex .rst tables.

I would like the ability to make spans that can be bigger than two consecutive cells.
Right now when I try that I'm getting `ERROR: This span is not valid:`

They actually don't break the rule of being a rectangular shape, so I was expecting it would *just* work.

A minimal example:
```python
import dashtable

spans = [
    [ [1, 0], [3, 0] ]
]
table = [
    ["Header 1", "Header 2", "Header 3"],
    ["row header", "Data1", "Data2"],
    ["", "Data3", "Data4"],
    ["", "Data5", "Data6"],
    ["row header2", "Data7", "Data8"],
]

print(dashtable.data2rst(table, spans))
```
I would like to obtain as output:

```
+-------------+----------+----------+
| Header 1    | Header 2 | Header 3 |
+=============+==========+==========+
| row header  | Data1    | Data2    |
|             +----------+----------+
|             | Data3    | Data4    |
|             +----------+----------+
|             | Data5    | Data6    |
+-------------+----------+----------+
| row header2 | Data7    | Data8    |
+-------------+----------+----------+
```
Do you think is possible to implement? 

thanks for considering

**Comment by doakey3** [comment]
In order for spans to work, they need to be of continuous cells. If you add the cell in between row 1 and 3, you get the desired result:

```python
import dashtable

spans = [
    [ [1, 0], [2, 0], [3, 0] ]
]
table = [
    ["Header 1", "Header 2", "Header 3"],
    ["row header", "Data1", "Data2"],
    ["", "Data3", "Data4"],
    ["", "Data5", "Data6"],
    ["row header2", "Data7", "Data8"],
]

print(dashtable.data2rst(table, spans))
```

**Comment by arielzn** [comment]
Oh, I see. 
Re-reading the doc https://dashtable.readthedocs.io/en/latest/Code.html#dashtable.data2rst , I see that the explanation considers that possibility.

But I must confess that I got faster how it works by looking at the example below.

As a suggestion, maybe it would help if on the example it is included explicitly a 3-cell span case (row or column), as the spans shown are all considering just a pair of cells

```python
>>> spans = [
...     [ [3, 1], [4, 1] ],
...     [ [3, 2], [4, 2] ],
...     [ [2, 1], [2, 2] ],
... ]
```
 

Thanks again for the lib, it works flawlessly.
