### ISSUE TITLE
Problem with HTML input.

### ISSUE THREAD

**Issue by virtualritz** [doakey3/DashTable#6]
Try attached HTML, it is exported from an e-mail generated by MS Office.
Only the column titles and 2/3 of the first row get printed, the rest is empty cells.

```
from dashtable import html2rst
filepath = "number.html"
print(html2rst(filepath, force_headers=False))
```
[number.html.zip](https://github.com/doakey3/DashTable/files/793417/number.html.zip)

**Comment by doakey3** [comment]
I made a couple of changes and it seems to be working now. Thanks for reporting your issue.
